In [1]:
get_ipython().run_line_magic('pylab', 'inline')
import numpy as np

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
#### We start with positive weights that don't sum to 1
P=np.array([[8.,6,7],[5,1,3]])
P2=copy(P)
P

array([[8., 6., 7.],
       [5., 1., 3.]])

In [3]:
# We then normalize the weights
# using Pure Python

#Compute the sum
s=0
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        s+=P[i,j]
print('the sum is ',s)
#divide by the sum
for i in range(shape(P)[0]):
    for j in range(shape(P)[1]):
        P[i,j] /= s
P

the sum is  30.0


array([[0.26666667, 0.2       , 0.23333333],
       [0.16666667, 0.03333333, 0.1       ]])

In [4]:
# Using Numpy we can write it in a much shorter way
P2/=sum(P2)
P2

array([[0.26666667, 0.2       , 0.23333333],
       [0.16666667, 0.03333333, 0.1       ]])

In [5]:
# The values that the random variables x and y take
x=np.array([2,3,5])
y=np.array([-1,1])

In [6]:
# The pure python way
Px=[0.]*shape(P)[1]
Py=[0.]*shape(P)[0]

for i in range(len(Px)):
    for j in range(len(Py)):
        Px[i]+=P[j,i]
        Py[j]+=P[j,i]
Px,Py

([0.43333333333333335, 0.23333333333333334, 0.33333333333333337], [0.7, 0.3])

In [7]:
#the numpy way:
Px=sum(P,axis=0)
Py=sum(P,axis=1)
Px,Py

(array([0.43333333, 0.23333333, 0.33333333]), array([0.7, 0.3]))

In [8]:
# The pure python way
for i in range(len(Px)):
    for j in range(len(Py)):
        if Px[i]*Py[j] != P[j,i]:
            print("Px[%d]*Py[%d] != P[%d,%d] ::::: %5.3f*%5.3f = %5.3f != %5.3f"%(i,j,j,i,Px[i],Py[j],Px[i]*Py[j],P[j,i]))

Px[0]*Py[0] != P[0,0] ::::: 0.433*0.700 = 0.303 != 0.267
Px[0]*Py[1] != P[1,0] ::::: 0.433*0.300 = 0.130 != 0.167
Px[1]*Py[0] != P[0,1] ::::: 0.233*0.700 = 0.163 != 0.200
Px[1]*Py[1] != P[1,1] ::::: 0.233*0.300 = 0.070 != 0.033


In [9]:
# The numpy way
np.outer(Px,Py).T - P

array([[ 0.03666667, -0.03666667,  0.        ],
       [-0.03666667,  0.03666667,  0.        ]])

In [10]:
from math import sqrt
#The python way
Ex = 0
for i in range(3):
    Ex+=Px[i]*x[i]
Ey = 0
for i in range(2):
    Ey+=Py[i]*y[i]

varx = 0
for i in range(3):
    varx+=Px[i]*(x[i] - Ex)**2
stdx = sqrt(varx)

vary = 0
for i in range(2):
    vary+=Py[i]*(y[i] - Ey)**2
stdy = sqrt(vary)

Ex,Ey,stdx,stdy

(3.2333333333333334,
 -0.39999999999999997,
 1.3085190950927015,
 0.9165151389911679)

In [11]:
# In numpy you can use np.dot(A,B) which calculates the pairwise product of elements in A and B
# and sums them up
Ex=np.dot(Px,x)
Ey=np.dot(Py,y)
Ex2=np.dot(Px,x**2)
Ey2=np.dot(Py,y**2)
stdx=sqrt(Ex2-Ex**2)
stdy=sqrt(Ey2-Ey**2)
print('Ex=%f,Ey=%f,stdx=%f,stdy=%f'%(Ex,Ey,stdx,stdy))

Ex=3.233333,Ey=-0.400000,stdx=1.308519,stdy=0.916515


In [12]:
nx=x-Ex
nx

array([-1.23333333, -0.23333333,  1.76666667])

In [13]:
ny=y-Ey
ny

array([-0.6,  1.4])

In [14]:
# in python
s=0
for i in range(len(x)):
    for j in range(len(y)):
        s+=P[j,i]*nx[i]*ny[j]
print('the covariance is',s) #our expected values are now 0 so nothing to subtract

the covariance is -0.07333333333333333


In [15]:
# numpy

print('the covariance is', np.dot(P.flatten(), np.outer(ny,nx).flatten()))

the covariance is -0.0733333333333333


In [16]:
import math
# Finding the variance is essential before calculating the standard deviation
def varinc(val, ddof=0):
    n = len(val)
    m = sum(val) / n
    return sum((x - m) ** 2 for x in val) / (n - ddof)
# finding the standard deviation
def stddev(val):
    vari = varinc(val)
    stdev = math.sqrt(vari)
    return stdev

print(stddev([5, 9, 6, 2, 6, 3, 7, 4, 8, 6]))

2.0591260281974004


C:\Users\jaisaini\AppData\Local\Temp\ipykernel_3760\1382792382.py:6: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return sum((x - m) ** 2 for x in val) / (n - ddof)
